--1
--select country from country where country ilike 'A%a';
--2
--select country from country where  country like '______%' and country like '%n';
--3
--select title from film where title ilike '%t%t%t%t%';
--4
--select * from film where title like 'C%' and length >90 and rental_rate=2.99;
